version: 2

build:
   os: ubuntu-22.04
   tools:
     python: "mambaforge-22.9"
   jobs:
     post_create_environment:
       - conda install python=3.8
       - conda install -c conda-forge pandoc<4

python:
    install:
        - method: pip
          path: .
          extra_requirements:
              - doc