version: 2

build:
   os: ubuntu-22.04
   tools:
     python: "mambaforge-22.9"

conda:
  environment: readthedocs-environment.yml

python:
    install:
        - method: pip
          path: .
          extra_requirements:
              - doc